<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Generates C# typed bindings for .resx files</Description>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>resgen</AssemblyName>
    <OutputType>Exe</OutputType>
    <TieredCompilation>true</TieredCompilation>
    <TieredCompilationQuickJit>true</TieredCompilationQuickJit>
    <RuntimeIdentifiers>rhel.9-s390x</RuntimeIdentifiers>
  </PropertyGroup>

</Project>
